[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$731vjZGSEkLIGeN87z2HEA$nk1NjVC4hf0FSDt8lHCqdrHIw178YjQoHMDQPqUnGbot5XTrHej5txEUd2q02eyZQ58vcGitaXbnNJyeQ2WBag
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
data_dir = /var/lib/odoo
log_level = info

