[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$s/a.FyIEgHBOSYlRSqn1Pg$VpCm6QUNe2yG4R1zlCXKlQe1K2X.vKX30uUsEXKarDEx/jmyf/tOv0To4x63m7LstKEh9VMm1Q.0RK4/K1EHEg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
data_dir = /var/lib/odoo
log_level = info

